name: Checkout Workflow
on: push
jobs:
    checkout-and-display:
        runs-on: ubuntu-latest
        steps:
            - name: List of files before
              run: ls -al
            - name: Checkout
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}"@github.com/$GITHUB_REPOSITORY.git
                git fetch origin
                git switch main
            - name: List files After
              run: ls -al
